import { readFile } from "node:fs/promises";
import path from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import { describe, expect, it } from "vitest";
import { repositoryRoot } from "./helpers.js";

// @ts-expect-error Repository release tooling is a directly executable ESM module.
const release = await import("../scripts/release/core.mjs");
// @ts-expect-error Repository release tooling is a directly executable ESM module.
const releaseSetModule = await import("../scripts/release/release-set.mjs");

// The 0.71 release set is generated by the later release task, so the 0.71
// manifest construction is exercised end to end by the adopter suite's
// substituted candidate archive; here the predecessor 0.7 manifest verifies
// against genuine release-set bytes and the current 0.71 schema verifies its
// strict compile and exact authority binding.
const schemaPath = path.join(repositoryRoot, "contracts/nkf/0.7/schemas/release-manifest.schema.json");
const currentSchemaPath = path.join(repositoryRoot, "contracts/nkf/0.71/schemas/release-manifest.schema.json");

async function compileSchema(file: string) {
  const AjvConstructor = Ajv2020 as unknown as new (options: Record<string, unknown>) => any;
  const ajv = new AjvConstructor({ allErrors: true, strict: true, validateFormats: true });
  const addFormatSupport = addFormats as unknown as (instance: any) => void;
  addFormatSupport(ajv);
  ajv.addKeyword({ keyword: "x-nkf-source" });
  return ajv.compile(JSON.parse((await readFile(file)).toString("utf8")));
}

async function compiled() {
  const AjvConstructor = Ajv2020 as unknown as new (options: Record<string, unknown>) => any;
  const ajv = new AjvConstructor({ allErrors: true, strict: true, validateFormats: true });
  const addFormatSupport = addFormats as unknown as (instance: any) => void;
  addFormatSupport(ajv);
  ajv.addKeyword({ keyword: "x-nkf-source" });
  return ajv.compile(JSON.parse((await readFile(schemaPath)).toString("utf8")));
}

async function realManifest(): Promise<Record<string, any>> {
  // Predecessor member bytes come from the exact published 0.7 archive; the
  // working tree no longer carries the predecessor projection bytes.
  const releaseSet = await releaseSetModule.readReleaseSet(repositoryRoot, "0.7");
  const archiveBytes = await readFile(path.join(
    repositoryRoot,
    ".nourd/tools/nkf/releases/nourd-nkf-sha256-c5ee783cd56c75fff2b19e8ae897e70954be2a82a6f0ce646270dc059c3df94f.tar",
  ));
  const entries = release.inspectUstar(archiveBytes) as Map<string, Buffer>;
  entries.delete("release-manifest.json");
  return release.constructReleaseManifest({
    releaseCommit: "a".repeat(40),
    entries,
    nkfVersion: "0.7",
    releaseSet,
  });
}

describe("NKF release-manifest schemas", () => {
  it("compiles strictly and accepts the exact constructed 0.7 manifest", async () => {
    const validate = await compiled();
    const manifest = await realManifest();
    expect(validate(manifest), JSON.stringify(validate.errors ?? []).slice(0, 400)).toBe(true);
  });

  it("compiles the current 0.71 schema strictly with the exact authority binding", async () => {
    const validate = await compileSchema(currentSchemaPath);
    const schema = JSON.parse((await readFile(currentSchemaPath)).toString("utf8"));
    expect(schema.$id).toBe("urn:nkf:0.71:schema:release-manifest");
    expect(schema["x-nkf-source"]).toMatchObject({
      nkf_version: "0.71",
      markdown_path: "knowledge/specifications/nkf-0.71.md",
      executable_path: "contracts/nkf/0.71/nkf.yaml",
    });
    expect(schema.properties.nkf_version).toEqual({ const: "0.71" });
    // The predecessor manifest is not admissible under the current contract.
    const manifest = await realManifest();
    expect(validate(manifest)).toBe(false);
    const relabeled = structuredClone(manifest);
    relabeled.nkf_version = "0.71";
    // A version relabel alone cannot admit predecessor bindings: the schema
    // demands the current version-delta member coverage.
    expect(relabeled.files.some((file: { path: string }) =>
      file.path === "contracts/nkf/0.71/version-delta.yaml")).toBe(false);
  });

  it("rejects a manifest without the version-delta binding or with extra fields", async () => {
    const validate = await compiled();
    const manifest = await realManifest();
    const missingDelta = structuredClone(manifest);
    delete missingDelta.version_delta;
    expect(validate(missingDelta)).toBe(false);

    const extra = structuredClone(manifest);
    extra.unexpected = true;
    expect(validate(extra)).toBe(false);

    const wrongVersion = structuredClone(manifest);
    wrongVersion.nkf_version = "0.6";
    expect(validate(wrongVersion)).toBe(false);
  });
});
